# Generated by Django 4.2.4 on 2024-01-09 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcessRequest",
            fields=[
                (
                    "code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("key", models.CharField(max_length=255)),
                ("premisions", models.CharField(max_length=1024)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="lisence",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Type", models.CharField(max_length=100)),
                ("Activations", models.IntegerField()),
                ("Limit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RegDevice",
            fields=[
                ("key", models.CharField(max_length=255)),
                (
                    "Serial",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Key", models.CharField(max_length=255)),
                ("premisions", models.CharField(default="NONE", max_length=1024)),
                (
                    "Device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.regdevice"
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "req",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.acessrequest",
                    ),
                ),
            ],
        ),
    ]
