# Generated by Django 4.2.4 on 2024-01-09 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="lisence",
            new_name="apikey",
        ),
    ]
