# Generated by Django 4.2.7 on 2024-01-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_lisence_apikey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acessrequest",
            name="premisions",
        ),
        migrations.AddField(
            model_name="acessrequest",
            name="prem1",
            field=models.CharField(default="NONE", max_length=1024),
        ),
        migrations.AddField(
            model_name="acessrequest",
            name="prem2",
            field=models.CharField(default="NONE", max_length=1024),
        ),
        migrations.AddField(
            model_name="acessrequest",
            name="prem3",
            field=models.CharField(default="NONE", max_length=1024),
        ),
        migrations.AddField(
            model_name="acessrequest",
            name="prem4",
            field=models.CharField(default="NONE", max_length=1024),
        ),
        migrations.AddField(
            model_name="confcode",
            name="key",
            field=models.CharField(default="NONE", max_length=255),
        ),
    ]
