# Generated by Django 4.2.7 on 2024-01-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_acessrequest_premisions_acessrequest_prem1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acessrequest",
            name="aproval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="linkeduser",
            name="premisions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.acessrequest"
            ),
        ),
    ]
