# Generated by Django 4.2.7 on 2024-01-19 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_acessrequest_serial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessrequest",
            old_name="prem1",
            new_name="perm1",
        ),
        migrations.RenameField(
            model_name="acessrequest",
            old_name="prem2",
            new_name="perm2",
        ),
        migrations.RenameField(
            model_name="acessrequest",
            old_name="prem3",
            new_name="perm3",
        ),
        migrations.RenameField(
            model_name="acessrequest",
            old_name="prem4",
            new_name="perm4",
        ),
    ]
