# Generated by Django 4.2.4 on 2024-01-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encryption",
            fields=[
                (
                    "Owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Salt", models.CharField(default="0", max_length=500)),
                ("IV", models.CharField(default="0", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="PW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=255)),
                ("Password", models.CharField(blank=True, max_length=255)),
                ("URL", models.URLField(blank=True, default="https://google.com")),
                ("TOTP", models.CharField(blank=True, max_length=255)),
                ("Date_Created", models.DateField(default=django.utils.timezone.now)),
                (
                    "Notes",
                    models.CharField(blank=True, default="empty", max_length=500),
                ),
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
